download_url: https://galaxy.ansible.com/download/community-zabbix-2.1.0.tar.gz
format_version: 1.0.0
name: zabbix
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/community/zabbix/versions/2.1.0/
