download_url: https://galaxy.ansible.com/download/ansible-netcommon-5.1.2.tar.gz
format_version: 1.0.0
name: netcommon
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.1.2
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/netcommon/versions/5.1.2/
