download_url: https://galaxy.ansible.com/download/ansible-windows-2.1.0.tar.gz
format_version: 1.0.0
name: windows
namespace: ansible
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/ansible/windows/versions/2.1.0/
