collections:
  - name: community.zabbix
    version: 2.1.0

roles:
  - name: geerlingguy.apache
    version: 3.3.0
  - name: geerlingguy.php
    version: 5.0.1
  - name: geerlingguy.mysql
    version: 4.3.3